FROM python:3

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install -r requirements.txt
RUN pip install -i https://test.pypi.org/simple/ Airbnb==1.0.6

COPY . /app

ENTRYPOINT [ "flask" ]

CMD [ "run" ]


